### PR TITLE
Completed JS re-do Labs 1-3 Version A & B for ROT13 Cipher, Unit Converter, and Blackjack.

### PR DESCRIPTION
**Pull request by ktabusa**
Completed Javascript Lab 05 Quote of the Day submitted and ready for review. Lab previously referenced incorrectly as lab 06.

### CODE REVIEW

**Comment by ktabusa** [comment]
Completed Javascript Lab 05 Quote of the Day submitted and ready for review.  Lab previously referenced incorrectly as lab 06.

**Comment by ktabusa** [comment]
Completed JS mini-capstone ready for review.

**Comment by brucestull** [comment]
# [Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)

* **Lab 01 A** - ROT13
    * **Completed**
* **Lab 01 B**
    * **Needs Work**
        * Result needs to be displayed in an HTML element instead of an 'alert' pop-up. See image below.
* **Lab 02 A**
    * **Completed**
        * The program could be improved by providing the user with a list of appropriate values for unit input values when prompting them for the unit input value. Some statement similar to the following:
            * `Please enter units ('in', 'ft', 'm', 'mi')`
* **Lab 02 B**
    * **Needs Work**
        * Result needs to be displayed in an HTML element instead of an 'alert' pop-up. See image below.
* **Lab 03 A**
    * **Completed**
* **Lab 03 B**
    * **Needs Work**
        * Result needs to be displayed in an HTML element instead of an 'alert' pop-up. See image below.

image
image
image

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
* **Needs Work**
    * See https://github.com/PdxCodeGuild/class_swordfish/pull/232#issuecomment-1338142635
    * Need to display results for DOM labs in some HTML element on the page. See me or Anthony if you need any assistance.

**Comment by ktabusa** [comment]
Completed Django Lab03 Chirp MVP ready for review.

**Comment by ktabusa** [comment]
Completed Lab 04 Students API ready for review.

**Comment by brucestull** [comment]
[Lab 3: Chirp (Twitter Clone)](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/03%20Chirp.md)
**Completed**

[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
* DOM Manipulation (Part B)
    * Lab 02 B
        * **Completed**

**Review by brucestull — APPROVED** [review]
[Lab 3: Chirp (Twitter Clone)](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/03%20Chirp.md)
**Completed**

[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
* DOM Manipulation (Part B)
    * Lab 02 B
        * **Completed**

[Lab 04 - Django REST Framework - Students API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20Students%20API.md)
**Completed**

See https://github.com/PdxCodeGuild/class_swordfish/pull/232#issuecomment-1343084547

**Pull request merged**
