### PR TITLE
Billy Frick - Django lab 4 (ready for review), JavaScript lab 6 (incomplete)

### PR DESCRIPTION
**Pull request by GirthyGnome**
JavaScript Lab 6 is not ready for review/merge.

### CODE REVIEW

**Review by Faebaeee — CHANGES_REQUESTED** [review]
Code looks good but is not running properly, try giving it a fix and let me know if you need any help!

**Comment by GirthyGnome** [comment]
pushed changes for Lab 4 (ready for re-review). JS Lab 6 is not ready to be merged into main.

**Review by Faebaeee — CHANGES_REQUESTED** [review]
Hey Billy, it's still not working properly. Try taking a look at your routes and see where they are going. Let me know if you need any help! I'll attach a photo of what im getting when i try your route. It should be students information.
Screen Shot 2022-11-28 at 5 01 47 PM

**Review by brucestull — APPROVED** [review]
[Lab 04 - Django REST Framework](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20DRF%20Vue.md)
**Completed**

**Review by Faebaeee — APPROVED** [review]

**Review by brucestull — APPROVED** [review]
[Lab 04 - Django REST Framework](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/04%20DRF%20Vue.md)
**Completed**

**Pull request merged**
