### PR TITLE
Billy Frick - JavaScript/Vue To-Do & Django Lab 3 (both ready for review). JS lab 5 is not ready to be reviewed or merged.

### PR DESCRIPTION
**Pull request by GirthyGnome**
To-do list made in Vue/JS is complete and ready for review.

### CODE REVIEW

**Comment by GirthyGnome** [comment]
pushed JavaScript labs 1-3, part b, after initial pull request for lab 4. All labs that have been pushed are ready for review.

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 4: Vue Todos](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2004%20Vue%20Todos.md)
**Needs Work**
* Comments:
    * `Allow a user to toggle if a task is complete or not`
        * There is a drop-down (select box) which lets user choose `Incomplete` or `Complete` options, but the data is not being saved anywhere.
        * App needs to save to the Vue object some way to specify if the todo is completed or not.
            * See me if you have any questions.

[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
* Lab 01 - BlackJack
    **Needs Work**
        * No advice provided for three `8`s:
            * Advice should be something like user is already busted, score above 21.
* Lab 02 - ROT 13
    **Completed**
* Lab 03 - Unit Converter
    **Completed**

**Comment by GirthyGnome** [comment]
adjusted required changes for blackjack lab, part b and the Vue Todo.

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 1-3: Pick 3](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2001-03%20Pick%203.md)
Lab 01 BlackJack
**Completed**
* Comments:
    * `Bust! LOSER!!` LOL Awesome!

[Lab 4: Vue Todos](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2004%20Vue%20Todos.md)
**Needs Work**
* Lab description: `Allow a user to toggle if a task is complete or not`:
    * Application needs to allow user to toggle the item between complete and incomplete.

**Comment by GirthyGnome** [comment]
HTML file (line 39 added), JS file (line 40-45 added). The user can now toggle between complete and incomplete.

**Comment by brucestull** [comment]
Lab 4 ToDos:
* Individual items are being rewritten incorrectly when toggling.
* Issue was demonstrated to student.
* Student will investigate.

**Comment by brucestull** [comment]
JavaScript Lab 4:
* Need to set input element text field to empty string at end of add method.
Chirp Lab:
* `login` and `logout` success URL set.

**Comment by GirthyGnome** [comment]
pushed changed discussed in breakout room. Refer to Django lab_03 settings.py (line 129 and 130) and JS lab 4 (line 19) for changes pushed. I also removed the extra user profile class in Django lab_03 (users/views.py), as it was leftover code from a previous attempt at Chirp.

**Review by brucestull — APPROVED** [review]
[Lab 4: Vue Todos](https://github.com/PdxCodeGuild/class_swordfish/blob/main/4%20JavaScript/labs/Lab%2004%20Vue%20Todos.md)
**Completed**

[Lab 3: Chirp (Twitter Clone)](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/03%20Chirp.md)
**Completed**
* Comments:
    * Good addition of login and logout success URLs.
    * NOTE:
        * A `Pipfile` and `Pipfile.lock` should be included with your django labs so the user of your app (me or anyone else) can use those to use the proper application packages and versions. Let me know if you need a review on this.

**Pull request merged**
