### PR TITLE
Rachel

### PR DESCRIPTION
**Pull request by junedeor**

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 7: Compute Automated Readability Index](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/07%20ARI.md)

Needs Work
* Sample file needs to be submitted with lab.

**Comment by junedeor** [comment]
Is this what you are looking for?
[gettysburg.txt](https://github.com/PdxCodeGuild/class_swordfish/files/9611854/gettysburg.txt)

**Comment by brucestull** [comment]
> Is this what you are looking for? [gettysburg.txt](https://github.com/PdxCodeGuild/class_swordfish/files/9611854/gettysburg.txt)

Almost:

* The file `gettysburg.txt` should be added and commited in `code\rachel\Python` as a sibling file to the lab file. So reviewer can `git checkout` your branch and run the code without having to copy paste code or files.
* See me if you have any further questions.

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 7: Compute Automated Readability Index](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/07%20ARI.md)

**Needs Work**

* Comments:
    * Please add the `gettysburg.txt` file to your directory on your branch so it is included with your code.

**Review by brucestull — APPROVED** [review]
[Lab 7: Compute Automated Readability Index](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/07%20ARI.md)
**Completed**

[Lab 9: ATM](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/09%20ATM.md)
**Completed**

[Lab 10: Dad Joke API](https://github.com/PdxCodeGuild/class_swordfish/blob/main/1%20Python/labs/10%20Dad%20Joke%20API.md)
**Completed**

* Comments:
    * Good work.

**Pull request merged**
