### PR TITLE
Lab 6 Ready for review

### PR DESCRIPTION
**Pull request by junedeor**

### CODE REVIEW

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 4: Burrito Order Form](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/04%20Burrito%20Order%20Form.md)
**Needs Work**
* Comments:
    * Great design and flavor text.
    * Very creative.
* Needed changes:
    * Lab needs to send `webhook.site` to api:
        * `Delivery Instructions` not showing at `webhook.site`:
image

**Comment by junedeor** [comment]
I'm not sure what you mean by "send web hook.site to api" - is there something I need to do with the web hook site / url besides adding it to <form action="webhook url" method="post"> line?

**Comment by brucestull** [comment]
> I'm not sure what you mean by "send web hook.site to api" - is there something I need to do with the web hook site / url besides adding it to the form action="webhook url" method="post" line?

I meant the following:
* Lab needs to send `Delivery Instructions` to api:

The application is not sending the "Delivery Instructions" to the api.

**Comment by junedeor** [comment]
Django Lab 1 login: rdcleav / 3edc#EDC

**Review by brucestull — CHANGES_REQUESTED** [review]
[Lab 4: Burrito Order Form](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/04%20Burrito%20Order%20Form.md)
**Completed**

[Lab 1: Grocery List](https://github.com/PdxCodeGuild/class_swordfish/blob/main/3%20Django/labs/01%20Grocery%20List.md)
**Needs Work**
* Comments:
    * I'm not sure which lab to grade, there are two directories with names like "Lab 1".
    * 
image

**Comment by junedeor** [comment]
IRT Lab 1: it's grocery list_lab01 (I had to redo it meh)

**Comment by brucestull** [comment]
[Lab 5: Flask Redo](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/05%20Flask%20Redo.md)
**Completed**

**Comment by junedeor** [comment]
Folder structure updated for Django Lab 1 and it's ready for review

**Review by brucestull — CHANGES_REQUESTED** [review]
[]()
**Needs Work**
* Comments:
    * URL `/grocerylist_lab01/` results in `Exception Value` error:
        * `Exception Value: Invalid block tag on line 31: 'end', expected 'empty' or 'endfor'. Did you forget to register or load this tag?`
image

**Review by brucestull — APPROVED** [review]
[Lab 6: Personal Portfolio](https://github.com/PdxCodeGuild/class_swordfish/blob/main/2%20Flask%20%2B%20HTML%20%2B%20CSS/labs/06%20Personal%20Portfolio.md)
**Completed**

**Pull request merged**
